/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ReturnPolicyRouteImport } from './routes/return-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SoldCarsRouteImport } from './routes/sold-cars'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VedetteRouteImport } from './routes/vedette'
import { Route as CheckoutListingIdRouteImport } from './routes/checkout.$listingId'
import { Route as ListingsListingIdRouteImport } from './routes/listings.$listingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnPolicyRoute = ReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldCarsRoute = SoldCarsRouteImport.update({
  id: '/sold-cars',
  path: '/sold-cars',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VedetteRoute = VedetteRouteImport.update({
  id: '/vedette',
  path: '/vedette',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutListingIdRoute = CheckoutListingIdRouteImport.update({
  id: '/checkout/$listingId',
  path: '/checkout/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/sold-cars': typeof SoldCarsRoute
  '/terms': typeof TermsRoute
  '/vedette': typeof VedetteRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/sold-cars': typeof SoldCarsRoute
  '/terms': typeof TermsRoute
  '/vedette': typeof VedetteRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/return-policy': typeof ReturnPolicyRoute
  '/shop': typeof ShopRoute
  '/sold-cars': typeof SoldCarsRoute
  '/terms': typeof TermsRoute
  '/vedette': typeof VedetteRoute
  '/checkout/$listingId': typeof CheckoutListingIdRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/favorites'
    | '/privacy'
    | '/refund-policy'
    | '/return-policy'
    | '/shop'
    | '/sold-cars'
    | '/terms'
    | '/vedette'
    | '/checkout/$listingId'
    | '/listings/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/favorites'
    | '/privacy'
    | '/refund-policy'
    | '/return-policy'
    | '/shop'
    | '/sold-cars'
    | '/terms'
    | '/vedette'
    | '/checkout/$listingId'
    | '/listings/$listingId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/favorites'
    | '/privacy'
    | '/refund-policy'
    | '/return-policy'
    | '/shop'
    | '/sold-cars'
    | '/terms'
    | '/vedette'
    | '/checkout/$listingId'
    | '/listings/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReturnPolicyRoute: typeof ReturnPolicyRoute
  ShopRoute: typeof ShopRoute
  SoldCarsRoute: typeof SoldCarsRoute
  TermsRoute: typeof TermsRoute
  VedetteRoute: typeof VedetteRoute
  CheckoutListingIdRoute: typeof CheckoutListingIdRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-policy': {
      id: '/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ReturnPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold-cars': {
      id: '/sold-cars'
      path: '/sold-cars'
      fullPath: '/sold-cars'
      preLoaderRoute: typeof SoldCarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vedette': {
      id: '/vedette'
      path: '/vedette'
      fullPath: '/vedette'
      preLoaderRoute: typeof VedetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$listingId': {
      id: '/checkout/$listingId'
      path: '/checkout/$listingId'
      fullPath: '/checkout/$listingId'
      preLoaderRoute: typeof CheckoutListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReturnPolicyRoute: ReturnPolicyRoute,
  ShopRoute: ShopRoute,
  SoldCarsRoute: SoldCarsRoute,
  TermsRoute: TermsRoute,
  VedetteRoute: VedetteRoute,
  CheckoutListingIdRoute: CheckoutListingIdRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
